export type GuardPolicy={response_sla_minutes:number;spend_without_lead:number;target_cpl:number;cpl_warning_multiplier:number;cpl_critical_multiplier:number;unattended_warning_percent:number;unattended_critical_percent:number;stale_ad_days:number;ai_enabled:boolean};
export type GuardInput={status:string;recentSpend:number;recentLeads:number;previousSpend?:number;previousLeads?:number;dashboardLeads:number;unattempted:number;staleUnattempted:number;ageDays:number;clicks:number;impressions?:number;dailyBudget?:number;syncFresh:boolean};
export type GuardResult={severity:"critical"|"warning"|"opportunity"|"healthy";code:string;title:string;reason:string;action:"pause"|"assign_leads"|"replace_creative"|"review_tracking"|"monitor";score:number;evidence:Record<string,number|boolean>};
export const defaultGuardPolicy:GuardPolicy={response_sla_minutes:120,spend_without_lead:750,target_cpl:150,cpl_warning_multiplier:1.5,cpl_critical_multiplier:2.5,unattended_warning_percent:25,unattended_critical_percent:50,stale_ad_days:14,ai_enabled:true};
export function evaluateAdGuard(x:GuardInput,p:GuardPolicy=defaultGuardPolicy):GuardResult{
 const active=x.status.toLowerCase()==="active", cpl=x.recentLeads?x.recentSpend/x.recentLeads:0, unattendedPct=x.dashboardLeads?x.staleUnattempted/x.dashboardLeads*100:0;
 const ctr=x.impressions?x.clicks/x.impressions*100:0, clickToLead=x.clicks?x.recentLeads/x.clicks*100:0, previousLeads=Number(x.previousLeads||0), previousSpend=Number(x.previousSpend||0);
 const evidence={recentSpend:Math.round(x.recentSpend),recentLeads:x.recentLeads,previousSpend:Math.round(previousSpend),previousLeads,dashboardLeads:x.dashboardLeads,unattempted:x.unattempted,staleUnattempted:x.staleUnattempted,unattendedPercent:Math.round(unattendedPct),cpl:Math.round(cpl),clicks:x.clicks,impressions:Number(x.impressions||0),ctr:Number(ctr.toFixed(2)),clickToLead:Number(clickToLead.toFixed(2)),ageDays:x.ageDays,syncFresh:x.syncFresh};
 if(active&&!x.syncFresh&&x.recentSpend>0)return{severity:"warning",code:"tracking_stale",title:"Check data connection",reason:"This ad is spending, but its saved Meta status has not refreshed recently.",action:"review_tracking",score:70,evidence};
 if(active&&x.recentSpend>=p.spend_without_lead&&x.recentLeads===0)return{severity:"critical",code:"spend_no_leads",title:"Pause recommended",reason:`₹${Math.round(x.recentSpend)} spent in 7 days with no Meta leads.`,action:"pause",score:98,evidence};
 if(active&&x.staleUnattempted>=10&&unattendedPct>=p.unattended_critical_percent)return{severity:"critical",code:"unattended_critical",title:"Clear the backlog before adding spend",reason:`${x.staleUnattempted} of ${x.dashboardLeads} leads are beyond the response SLA (${Math.round(unattendedPct)}%).`,action:"assign_leads",score:95,evidence};
 if(active&&cpl>=p.target_cpl*p.cpl_critical_multiplier)return{severity:"critical",code:"cpl_critical",title:"Pause or replace creative",reason:`7-day CPL is ₹${Math.round(cpl)}, above the configured critical limit.`,action:"pause",score:92,evidence};
 if(active&&x.ageDays>=7&&previousLeads>=5&&x.recentLeads<=previousLeads*.5&&x.recentSpend>=previousSpend*.8)return{severity:"warning",code:"creative_fatigue",title:"Refresh the poster",reason:`Leads fell from ${previousLeads} to ${x.recentLeads} while spend stayed broadly similar. The creative is likely losing response.`,action:"replace_creative",score:88,evidence};
 if(active&&x.ageDays>=7&&x.recentLeads<3&&x.recentSpend>=p.target_cpl*1.5&&(x.clicks>=50||Number(x.impressions||0)>=2000))return{severity:"warning",code:"low_lead_volume",title:"Try a new poster or audience",reason:`Only ${x.recentLeads} leads came in over 7 days after ₹${Math.round(x.recentSpend)} spend. Delivery is sufficient, but response is weak.`,action:"replace_creative",score:84,evidence};
 if(active&&x.clicks>=80&&clickToLead<2)return{severity:"warning",code:"clicks_not_converting",title:"Review the form and targeting",reason:`${x.clicks} clicks produced only ${x.recentLeads} leads (${clickToLead.toFixed(1)}% conversion). The poster attracts clicks but not applications.`,action:"replace_creative",score:82,evidence};
 if(active&&Number(x.impressions||0)>=3000&&ctr<.7)return{severity:"warning",code:"weak_creative_hook",title:"Change the poster and message",reason:`The ad reached ${Number(x.impressions||0).toLocaleString("en-IN")} impressions, but CTR is only ${ctr.toFixed(2)}%. The creative is not attracting enough interest.`,action:"replace_creative",score:80,evidence};
 if(active&&x.staleUnattempted>=5&&unattendedPct>=p.unattended_warning_percent)return{severity:"warning",code:"unattended_warning",title:"Assign the pending leads today",reason:`${x.staleUnattempted} of ${x.dashboardLeads} leads are beyond the response SLA (${Math.round(unattendedPct)}%).`,action:"assign_leads",score:78,evidence};
 if(active&&cpl>=p.target_cpl*p.cpl_warning_multiplier)return{severity:"warning",code:"cpl_warning",title:"Review targeting and creative",reason:`7-day CPL is ₹${Math.round(cpl)}, above target.`,action:"replace_creative",score:72,evidence};
 if(active&&x.ageDays>=3&&Number(x.dailyBudget||0)>0&&x.recentSpend<Number(x.dailyBudget)*1.5)return{severity:"opportunity",code:"low_delivery",title:"Check audience size and approval",reason:`The ad spent only ₹${Math.round(x.recentSpend)} in 7 days against a ₹${Math.round(Number(x.dailyBudget))} daily budget. It is not delivering enough for a performance verdict.`,action:"monitor",score:55,evidence};
 if(active&&x.recentLeads>0&&cpl<=p.target_cpl&&unattendedPct<10)return{severity:"healthy",code:"performing",title:"Performing within policy",reason:`7-day CPL is ₹${Math.round(cpl)} and the response queue is controlled.`,action:"monitor",score:15,evidence};
 return{severity:"opportunity",code:"insufficient_signal",title:"Continue monitoring",reason:"There is not enough verified evidence for a spend intervention.",action:"monitor",score:30,evidence};
}
