'use client';
import { useEffect,useState } from 'react';
export default function AdMailPanel({token}:{token:string}){
 const [data,setData]=useState<any>(null);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 async function load(){const r=await fetch('/api/recruitment/ad-mail',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(r.ok)setData(await r.json());}
 useEffect(()=>{void load();},[token]);
 async function update(body:object){setBusy(true);setNotice('');try{const r=await fetch('/api/recruitment/ad-mail',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.error);setNotice('sent' in p?`${p.sent} samples sent to ${p.to}. Samples are limited to one pair per day.`:p.queued?'Retry queued for the next scheduled check.':'Schedule updated.');await load();}catch(e){setNotice(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 if(!data)return null;
 const attention=data.recent?.filter((r:any)=>['failed','needs_review'].includes(r.status))??[];
 return <details className="content-card" style={{padding:16,margin:'12px 0'}}><summary style={{cursor:'pointer',fontWeight:700}}>Manager emails · {data.enabled?'Live':'Off'} · 08:30 and 20:00 IST {attention.length?`· ${attention.length} need review`:''}</summary><div style={{paddingTop:12}}><p>Workforce ads only · one direct recipient mail for every mapped person · {data.recipientGroups} recipient groups. No blanket CC recipients.</p><p>The 08:30 message is a compact current-status table. The 20:00 message is a compact live, paused, ended and budget-change table. Each remains in its own monthly thread.</p>{data.unmappedStations?.length?<p role="alert">No mapped recipient: {data.unmappedStations.join(', ')}.</p>:null}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={busy} onClick={()=>void update({enabled:!data.enabled})}>{data.enabled?'Pause emails':'Enable emails'}</button><button disabled={busy} onClick={()=>void update({action:'sample'})}>Send both samples to me</button><button disabled={busy} onClick={()=>void load()}>Refresh log</button></div>{notice?<p role="status">{notice}</p>:null}<details style={{marginTop:12}}><summary>Recent delivery log ({data.recent?.length||0})</summary><table><thead><tr><th>Type</th><th>Status</th><th>Time (IST)</th><th>Note</th></tr></thead><tbody>{data.recent?.slice(0,30).map((r:any)=><tr key={r.id}><td>{r.kind}</td><td>{r.status}</td><td>{new Date(r.sent_at||r.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td>{r.error||'—'}{['failed','needs_review'].includes(r.status)?<button disabled={busy} onClick={()=>{if(r.status==='failed'||window.confirm('Check the mail provider first. Confirm that this message was NOT delivered to any recipient. Retrying can otherwise send a duplicate.'))void update({action:'retry',id:r.id,confirmedUndelivered:true});}}>Retry after verification</button>:null}</td></tr>)}</tbody></table></details></div></details>;
}
