import { resolveMailAction,submitMailAction } from '@/lib/ad-manager-mail';
import { redirect } from 'next/navigation';
export const dynamic='force-dynamic';
export const metadata={title:'DropX Recruit · Ad request',robots:{index:false,follow:false},referrer:'no-referrer' as const};
export default async function AdResponse({searchParams}:{searchParams:{token?:string;done?:string;error?:string}}){
 const token=searchParams.token||'';
 let context;try{context=await resolveMailAction(token);}catch{return <main style={{maxWidth:560,margin:'60px auto',padding:24}}><h1>Request link unavailable</h1><p>This link has expired or your station access has changed. Use your latest email or contact Workforce.</p></main>;}
 const {ad,person,action}=context;
 async function submit(form:FormData){'use server';let id:string;try{id=await submitMailAction(token,Number(form.get('headcount')),String(form.get('note')||'').trim());}catch{redirect(`/ad-response?token=${encodeURIComponent(token)}&error=1`);}redirect(`/ad-response?token=${encodeURIComponent(token)}&done=${encodeURIComponent(id)}`);}
 return <main style={{maxWidth:580,margin:'48px auto',padding:24,background:'white',borderRadius:16,boxShadow:'0 8px 40px #18233814'}}><p style={{color:'#dc245c',fontSize:12,fontWeight:800}}>DROPX RECRUIT · WORKFORCE</p><h1 style={{fontSize:26}}>{context.requestId?'Request received':action.action==='resume_ad'?'Request ad resume':'Ad no longer required'}</h1><p><strong>{ad.station} · {ad.role}</strong></p><p style={{color:'#667085',fontSize:13}}>{ad.ad_name}<br/>Requested by {person.name}</p>{context.requestId?<section role="status"><p>Your request is in <strong>Ad Requests</strong> for Workforce review.</p><p>No ad or budget has been changed.</p></section>:<form action={submit}>{searchParams.error?<p role="alert">Unable to submit. Check your details and try again.</p>:null}{action.action==='resume_ad'?<label style={{display:'block',margin:'20px 0'}}>Associates required<input name="headcount" type="number" min="1" max="1000" required style={{display:'block',width:'100%',padding:12,marginTop:8}}/></label>:null}<label style={{display:'block',margin:'20px 0'}}>Note (optional)<textarea name="note" maxLength={1000} rows={3} style={{display:'block',width:'100%',padding:12,marginTop:8}}/></label><p style={{fontSize:13,color:'#667085'}}>Workforce will review this request. Submitting does not pause, resume or spend on an ad.</p><button type="submit" style={{background:'#dc245c',color:'white',border:0,borderRadius:8,padding:'12px 20px',fontWeight:700}}>Send request</button></form>}</main>;
}
